import { userInfo } from "./user";

export const sampleUsersInfo: userInfo[] = [
    {
        user: {
            id: 1,
            name: "서정민",
            teamBuildingStatus: "WAITING",
        },
        briefIntroduction: "B2B SaaS 프로덕트 디자이너로 3년 경력",
        preferredTeamMember: "으쌰으쌰 함께, 재밌게 프로젝트 해나갈 팀 or 팀원을 찾고 있습니다.",
        availableParticipationTime: "주 2회 이상",
        employmentStatus: "CURRENTLY_WORKING",
        occupation: "DESIGNER",
        participationPurpose: "스킬 향상",
        keywords: ["협업", "기술 이해", "디자인 시스템"],
        strengths: ["UI/UX 툴", "프로젝트 경험", "커뮤니케이션"],
        skills: ["Figma", "Sketch", "Zeplin", "Adobe XD"],
        createdAt: "2021-10-01T00:00:00.000Z",
        updatedAt: "2021-10-01T00:00:00.000Z",
    },
    {
        user: {
            id: 2,
            name: "이형준",
            teamBuildingStatus: "IN_PROGRESS",
        },
        briefIntroduction: "FE 개발자 취업준비생",
        preferredTeamMember: "으쌰으쌰 함께, 재밌게 프로젝트 해나갈 팀 or 팀원을 찾고 있습니다.",
        availableParticipationTime: "주 5회 이상",
        employmentStatus: "PREPARING_FOR_EMPLOYMENT",
        occupation: "WEB_ENGINEER",
        participationPurpose: "포트폴리오",
        keywords: ["협업", "기술 이해", "디자인 시스템"],
        strengths: ["프레임워크 숙련도", "프로젝트 경험", "참여 시간"],
        skills: ["React", "Vue", "Angular", "Javascript"],
        createdAt: "2022-10-01T00:00:00.000Z",
        updatedAt: "2022-10-01T00:00:00.000Z",
    },
    {
        user: {
            id: 3,
            name: "신문기",
            teamBuildingStatus: "COMPLETED",
        },
        briefIntroduction: "BE 개발자",
        preferredTeamMember: "으쌰으쌰 함께, 재밌게 프로젝트 해나갈 팀 or 팀원을 찾고 있습니다.",
        availableParticipationTime: "주 3회 이상",
        employmentStatus: "CURRENTLY_WORKING",
        occupation: "SERVER_ENGINEER",
        participationPurpose: "재미",
        keywords: ["협업", "기술 이해", "디자인 시스템"],
        strengths: ["프레임워크 숙련도", "프로젝트 경험", "참여 시간"],
        skills: ["Node.js", "Express", "Spring", "Django"],
        createdAt: "2023-10-01T00:00:00.000Z",
        updatedAt: "2023-10-01T00:00:00.000Z",
    },
    {
        user: {
            id: 4,
            name: "박종헌",
            teamBuildingStatus: "WAITING",
        },
        briefIntroduction: "열정적인 기획자",
        preferredTeamMember: "으쌰으쌰 함께, 재밌게 프로젝트 해나갈 팀 or 팀원을 찾고 있습니다.",
        availableParticipationTime: "주 4회 이상",
        employmentStatus: "LOOKING_FOR_JOB",
        occupation: "PRODUCT_MANAGER",
        participationPurpose: "서비스 출시",
        keywords: ["협업", "기술 이해", "디자인 시스템"],
        strengths: ["커뮤니케이션", "업무 경험", "협업 툴 숙련도"],
        skills: ["Figma", "Sketch", "Zeplin", "Adobe XD"],
        createdAt: "2023-11-01T00:00:00.000Z",
        updatedAt: "2023-11-01T00:00:00.000Z",
    },
];
